/**
 * APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { Error1 } from '../models/error1';

/**
 * Creates an instance of Custom
 */
interface Custom {
  error: Error1;
}

export class CustomError extends ApiError<Custom> {}
