/**
 * APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core';
import { Feedback, feedbackSchema } from '../models/feedback';
import {
  ImpressionsSubjectsFeedbacksResponse,
  impressionsSubjectsFeedbacksResponseSchema,
} from '../models/impressionsSubjectsFeedbacksResponse';
import {
  ImpressionsSubjectsResponse,
  impressionsSubjectsResponseSchema,
} from '../models/impressionsSubjectsResponse';
import { Subject, subjectSchema } from '../models/subject';
import { array, optional, string } from '../schema';
import { BaseController } from './baseController';

export class ImpressionsController extends BaseController {
  /**
   * Delete feedback
   *
   * @param subjectId  Subject id
   * @param feedbackId Feedback id
   * @return Response from the API call
   */
  async deleteFeedback(
    subjectId: string,
    feedbackId: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ImpressionsSubjectsFeedbacksResponse>> {
    const req = this.createRequest('DELETE');
    const mapped = req.prepareArgs({
      subjectId: [subjectId, string()],
      feedbackId: [feedbackId, string()],
    });
    req.appendTemplatePath`/impressions/subjects/${mapped.subjectId}/feedbacks/${mapped.feedbackId}`;
    return req.callAsJson(
      impressionsSubjectsFeedbacksResponseSchema,
      requestOptions
    );
  }

  /**
   * Delete subject
   *
   * @param subjectId Subject id
   * @return Response from the API call
   */
  async deleteSubject(
    subjectId: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ImpressionsSubjectsResponse>> {
    const req = this.createRequest('DELETE');
    const mapped = req.prepareArgs({ subjectId: [subjectId, string()] });
    req.appendTemplatePath`/impressions/subjects/${mapped.subjectId}`;
    return req.callAsJson(impressionsSubjectsResponseSchema, requestOptions);
  }

  /**
   * Get a list of all subjects
   *
   * @return Response from the API call
   */
  async getSubjects(
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<Subject[]>> {
    const req = this.createRequest('GET', '/impressions/subjects');
    return req.callAsJson(array(subjectSchema), requestOptions);
  }

  /**
   * Get a list of all subject feedbacks
   *
   * @param subjectId Subject id
   * @return Response from the API call
   */
  async getFeedbacks(
    subjectId: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<Feedback[]>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({ subjectId: [subjectId, string()] });
    req.appendTemplatePath`/impressions/subjects/${mapped.subjectId}/feedbacks`;
    return req.callAsJson(array(feedbackSchema), requestOptions);
  }

  /**
   * Add feedback from user
   *
   * @param subjectId    Subject id
   * @param body
   * @return Response from the API call
   */
  async addUserFeedback(
    subjectId: string,
    body?: Feedback,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ImpressionsSubjectsFeedbacksResponse>> {
    const req = this.createRequest('POST');
    const mapped = req.prepareArgs({
      subjectId: [subjectId, string()],
      body: [body, optional(feedbackSchema)],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/impressions/subjects/${mapped.subjectId}/feedbacks`;
    return req.callAsJson(
      impressionsSubjectsFeedbacksResponseSchema,
      requestOptions
    );
  }
}
