/**
 * impressions-sdkLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { Result, resultSchema } from './result';

export interface ApikeysResponse {
  result?: Result;
}

export const apikeysResponseSchema: Schema<ApikeysResponse> = object({
  result: ['result', optional(lazy(() => resultSchema))],
});
