/**
 * APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface ApikeysRequest {
  name?: string;
}

export const apikeysRequestSchema: Schema<ApikeysRequest> = object({
  name: ['name', optional(string())],
});
