/**
 * impressions-sdkLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface Datum {
  name?: string;
}

export const datumSchema: Schema<Datum> = object({
  name: ['name', optional(string())],
});
