/**
 * impressions-sdkLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface Error1 {
  message: string;
  code: string;
  details?: string;
}

export const error1Schema: Schema<Error1> = object({
  message: ['message', string()],
  code: ['code', string()],
  details: ['details', optional(string())],
});
