/**
 * APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string, unknown } from '../schema';

export interface Feedback {
  value?: unknown;
  /** Optional ID of the user who provided feedback */
  userId?: string;
}

export const feedbackSchema: Schema<Feedback> = object({
  value: ['value', unknown()],
  userId: ['userId', optional(string())],
});
