/**
 * impressions-sdkLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string, unknown } from '../schema';

export interface Feedback {
  value?: unknown;
  /** Optional ID of the user who provided feedback */
  userId?: string;
  /** Id of a subject */
  subjectId?: string;
  /** Date of creation for feedback */
  createdAt?: string;
  /** Last updated at for feedback */
  updatedAt?: string;
  /** Id of feedback */
  id?: string;
}

export const feedbackSchema: Schema<Feedback> = object({
  value: ['value', unknown()],
  userId: ['userId', optional(string())],
  subjectId: ['subjectId', optional(string())],
  createdAt: ['createdAt', optional(string())],
  updatedAt: ['updatedAt', optional(string())],
  id: ['id', optional(string())],
});
