/**
 * APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { Result3, result3Schema } from './result3';

export interface ImpressionsSubjectsFeedbacksResponse {
  result?: Result3;
}

export const impressionsSubjectsFeedbacksResponseSchema: Schema<ImpressionsSubjectsFeedbacksResponse> = object(
  { result: ['result', optional(lazy(() => result3Schema))] }
);
