/**
 * APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface ImpressionsSubjectsResponse {
  /** Subject ID */
  id?: string;
}

export const impressionsSubjectsResponseSchema: Schema<ImpressionsSubjectsResponse> = object(
  { id: ['id', optional(string())] }
);
