/**
 * APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface ImpressionsSubjectsFeedbacksResponse {
  /** Feedback ID */
  id?: string;
}

export const impressionsSubjectsFeedbacksResponseSchema: Schema<ImpressionsSubjectsFeedbacksResponse> = object(
  { id: ['id', optional(string())] }
);
