/**
 * impressions-sdkLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { Result5, result5Schema } from './result5';

export interface ImpressionsSubjectsResponse1 {
  result?: Result5;
}

export const impressionsSubjectsResponse1Schema: Schema<ImpressionsSubjectsResponse1> = object(
  { result: ['result', optional(lazy(() => result5Schema))] }
);
