/**
 * APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { Result4, result4Schema } from './result4';

export interface ImpressionsSubjectsResponse {
  result?: Result4;
}

export const impressionsSubjectsResponseSchema: Schema<ImpressionsSubjectsResponse> = object(
  { result: ['result', optional(lazy(() => result4Schema))] }
);
