/**
 * impressions-sdkLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface Key {
  value: string;
  name: string;
  createdAt?: string;
  updatedAt: string;
  id: string;
}

export const keySchema: Schema<Key> = object({
  value: ['value', string()],
  name: ['name', string()],
  createdAt: ['createdAt', optional(string())],
  updatedAt: ['updatedAt', string()],
  id: ['id', string()],
});
