/**
 * APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, number, object, optional, Schema } from '../schema';
import { Subject, subjectSchema } from './subject';

export interface Result5 {
  /** Total number of subjects */
  total?: number;
  data?: Subject[];
}

export const result5Schema: Schema<Result5> = object({
  total: ['total', optional(number())],
  data: ['data', optional(array(lazy(() => subjectSchema)))],
});
