/**
 * impressions-sdkLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, number, object, optional, Schema } from '../schema';
import { Datum, datumSchema } from './datum';

export interface Result5 {
  /** Total number of subjects */
  total?: number;
  data?: Datum[];
}

export const result5Schema: Schema<Result5> = object({
  total: ['total', optional(number())],
  data: ['data', optional(array(lazy(() => datumSchema)))],
});
