/**
 * APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, number, object, optional, Schema } from '../schema';
import { Feedback, feedbackSchema } from './feedback';

export interface Result6 {
  /** Total number of feedbacks */
  total?: number;
  data?: Feedback[];
}

export const result6Schema: Schema<Result6> = object({
  total: ['total', optional(number())],
  data: ['data', optional(array(lazy(() => feedbackSchema)))],
});
