/**
 * impressions-sdkLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface Result3 {
  /** Feedback ID */
  id?: string;
}

export const result3Schema: Schema<Result3> = object({
  id: ['id', optional(string())],
});
