/**
 * impressions-sdkLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface Signup {
  email: string;
  password: string;
  name: string;
}

export const signupSchema: Schema<Signup> = object({
  email: ['email', string()],
  password: ['password', string()],
  name: ['name', string()],
});
