/**
 * APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface Subject {
  id?: string;
  createdAt?: string;
}

export const subjectSchema: Schema<Subject> = object({
  id: ['id', optional(string())],
  createdAt: ['created_at', optional(string())],
});
