/**
 * impressions-sdkLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

/** Access token */
export interface Token {
  /** Token value */
  value?: string;
  /** Type of token */
  type?: string;
}

export const tokenSchema: Schema<Token> = object({
  value: ['value', optional(string())],
  type: ['type', optional(string())],
});
